### PR TITLE
add validation on product title that is at least 10 characters long

### PR DESCRIPTION
**Pull request by mdr-uma**

### CODE REVIEW

**Review by cjilbert504 — CHANGES_REQUESTED** [review]
The test you added is passing the assertion but not because of failing the length validation. If you look in the fixtures file for products and look at what the title of the ruby row is you'll see that the title is "Programming Ruby 1.9" which is more than 10 characters so using that title should be valid. However, the test is passing because yes the product is invalid but only because that title already exists in the test db so the product is invalid bc it is failing the uniqueness validation. Try to make it so that the product being used in the test has a title that should fail the length validation please. Thank you!

**Comment by mdr-uma** [comment]
> The test you added is passing the assertion but not because of failing the length validation. If you look in the fixtures file for products and look at what the title of the ruby row is you'll see that the title is "Programming Ruby 1.9" which is more than 10 characters so using that title should be valid. However, the test is passing because yes the product is invalid but only because that title already exists in the test db so the product is invalid bc it is failing the uniqueness validation. Try to make it so that the product being used in the test has a title that should fail the length validation please. Thank you!

updated it. I hope that works. :)

**Review by cjilbert504 — APPROVED** [review]

**Comment by cjilbert504** [comment]
Looks good. Thank you!!!

**Comment by mdr-uma** [comment]
my pleasure :)

**Pull request merged**
